projects:
  korkbo:
    schemaPath: amplify/backend/api/korkbo/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 2
