/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://inqciqsjm5gvfke4ontfkqckyi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-u4u6o6sekfgo7dtqkh2ito5puu",
    "aws_cognito_identity_pool_id": "us-east-2:510cafcf-b93c-4921-a2a9-884bbbd4e98f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_y2lX1UNQQ",
    "aws_user_pools_web_client_id": "3pr75d1n0fec9temnjtefhju4g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "korkbo-storage-photos103823-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
