/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://zhidvwapfvbo5je2deoexguxva.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-afm6fpdfgfavza4neuygfsbqte",
    "aws_cognito_identity_pool_id": "us-west-1:40b7bcd1-a9ff-4aa8-896a-1a9dde9648af",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_lJaV8abKd",
    "aws_user_pools_web_client_id": "5mvceioe5g4vvaebfat5vetqhp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "korkbof3b8f9ace4cc4641b7954058899ccc71145707-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
